// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neystcbjrbwotggtlnys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5leXN0Y2JqcmJ3b3RnZ3RsbnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTQzMDUsImV4cCI6MjA2NTIzMDMwNX0.cPDd4Tk5s6U7BJ4siPtv6T4riWJ5wa_ed1efsD-Pf9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);